apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: storageos
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/croomes/kubectl-plugin/releases/download/v0.1.0/storageos_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./storageos"
      to: "."
    - from: LICENSE
      to: "."
    bin: "storageos"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/croomes/kubectl-plugin/releases/download/v0.1.0/storageos_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./storageos"
      to: "."
    - from: LICENSE
      to: "."
    bin: "storageos"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/croomes/kubectl-plugin/releases/download/v0.1.0/storageos_windows_amd64.zip
    sha256: ""
    files:
    - from: "/storageos.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "storageos.exe"
  shortDescription: A new plugin
  homepage: https://github.com/croomes/kubectl-plugin
  caveats: |
    Usage:
      $ kubectl storageos

    For additional options:
      $ kubectl storageos --help
      or https://github.com/croomes/kubectl-plugin/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
